#创建人行登陆薄记录表
CREATE
    TABLE rh.rh.RH_LOGIN_ZHENGXIN_WEB_LOG
    (
        ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
        USER_CODE VARCHAR(192),
        CUST_NAME VARCHAR(192),
        ORGCODE VARCHAR(192),
        USERID VARCHAR(192),
        PASSWORD VARCHAR(192),
        STATUS VARCHAR(192),
        UPLOADTIME TIMESTAMP,
        CLIENT_TYPE VARCHAR(10),
        ORG_NAME VARCHAR(15),
        SEARCH_TYPE VARCHAR(15),
        USER_NAME VARCHAR(50),
        USER_BRANCH_NAME VARCHAR(100),
        CUST_CODE VARCHAR(20),
        PRIMARY KEY (ID)
    );
COMMENT ON TABLE rh.RH_LOGIN_ZHENGXIN_WEB_LOG
IS
    '登陆人行征信页面查询详细记录日志表(rh.RH_LOGIN_ZHENGXIN_WEB_LOG)';
COMMENT ON COLUMN rh.RH_LOGIN_ZHENGXIN_WEB_LOG.ID
IS
    'id';
COMMENT ON COLUMN rh.RH_LOGIN_ZHENGXIN_WEB_LOG.USER_CODE
IS
    '发起查询的用户号';
COMMENT ON COLUMN rh.RH_LOGIN_ZHENGXIN_WEB_LOG.CUST_NAME
IS
    '企业名称';
COMMENT ON COLUMN rh.RH_LOGIN_ZHENGXIN_WEB_LOG.ORGCODE
IS
    '登陆人行征信页面使用的机构号码';
COMMENT ON COLUMN rh.RH_LOGIN_ZHENGXIN_WEB_LOG.USERID
IS
    '登陆人行征信页面使用的用户号';
COMMENT ON COLUMN rh.RH_LOGIN_ZHENGXIN_WEB_LOG.PASSWORD
IS
    '登陆人行征信页面使用的用户密码';
COMMENT ON COLUMN rh.RH_LOGIN_ZHENGXIN_WEB_LOG.STATUS
IS
    '爬取该企业后的状态0成功1失败';
COMMENT ON COLUMN rh.RH_LOGIN_ZHENGXIN_WEB_LOG.UPLOADTIME
IS
    '登陆人行征信页面的入库时间';
COMMENT ON COLUMN rh.RH_LOGIN_ZHENGXIN_WEB_LOG.CLIENT_TYPE
IS
    '联机标志0是本地1是联机';
COMMENT ON COLUMN rh.RH_LOGIN_ZHENGXIN_WEB_LOG.ORG_NAME
IS
    '用户所属机构';
COMMENT ON COLUMN rh.RH_LOGIN_ZHENGXIN_WEB_LOG.SEARCH_TYPE
IS
    '查询类型';
COMMENT ON COLUMN rh.RH_LOGIN_ZHENGXIN_WEB_LOG.USER_NAME
IS
    '联机查询征信用户名';
COMMENT ON COLUMN rh.RH_LOGIN_ZHENGXIN_WEB_LOG.USER_BRANCH_NAME
IS
    '用户所属部门';
COMMENT ON COLUMN rh.RH_LOGIN_ZHENGXIN_WEB_LOG.CUST_CODE
IS
    '企业组织机构代码'

#创建征信爬虫客户清单表
CREATE TABLE rh.RISK_MNIT_QUERY_RH_LIST
    (
    	  QUERY_ID BIGINT NOT NULL,
	 			ENT_NAME VARCHAR(300),
        CUS_NO VARCHAR(100),
        MID_SIGN_CODE VARCHAR(100),
        CUST_CODE    VARCHAR(100),
        CLIENT_TYPE  VARCHAR(2),
        USER_NAME VARCHAR(100),
        USER_CODE VARCHAR(11),
        USER_BRANCH_ID VARCHAR(11),
        USER_BRANCH_NAME VARCHAR(128),
        USER_ORG_ID VARCHAR(11),
        USER_ORG_NAME VARCHAR(150),
        QUERY_REASON VARCHAR(100),
        QUERY_FOR VARCHAR(100),
        FILE_NAME VARCHAR(300),
        ECM_DOC_ID  VARCHAR(26),
        QUERY_TIME TIMESTAMP DEFAULT CURRENT TIMESTAMP,
        CONSTRAINT P_ID PRIMARY KEY (QUERY_ID)
    );
COMMENT ON TABLE RISK_MNIT_QUERY_RH_LIST
IS
    '风险监测待查询企业征信清单';
COMMENT ON COLUMN rh.RISK_MNIT_QUERY_RH_LIST.QUERY_ID
IS
    '内部自增主键';
COMMENT ON COLUMN rh.RISK_MNIT_QUERY_RH_LIST.ENT_NAME
IS
    '企业名称';
COMMENT ON COLUMN rh.RISK_MNIT_QUERY_RH_LIST.USER_NAME
IS
    '用户名称';
COMMENT ON COLUMN rh.RISK_MNIT_QUERY_RH_LIST.CUS_NO
IS
    '客户号';
COMMENT ON COLUMN rh.RISK_MNIT_QUERY_RH_LIST.MID_SIGN_CODE
IS
   '企业中征码';
COMMENT ON COLUMN rh.RISK_MNIT_QUERY_RH_LIST.CUST_CODE
IS
   '企业组织机构代码';
COMMENT ON COLUMN rh.RISK_MNIT_QUERY_RH_LIST.CLIENT_TYPE
IS
   '是否联机查询';
COMMENT ON COLUMN rh.RISK_MNIT_QUERY_RH_LIST.USER_CODE
IS
    '用户CODE';
COMMENT ON COLUMN rh.RISK_MNIT_QUERY_RH_LIST.USER_BRANCH_ID
IS
    '用户所属分行ID';
COMMENT ON COLUMN rh.RISK_MNIT_QUERY_RH_LIST.USER_BRANCH_NAME
IS
    '用户所属分行名称';
COMMENT ON COLUMN rh.RISK_MNIT_QUERY_RH_LIST.USER_ORG_ID
IS
    '用户归属机构';
COMMENT ON COLUMN rh.RISK_MNIT_QUERY_RH_LIST.USER_ORG_NAME
IS
    '用户归属机构名称';
COMMENT ON COLUMN rh.RISK_MNIT_QUERY_RH_LIST.QUERY_REASON
IS
    '查询类型';
COMMENT ON COLUMN rh.RISK_MNIT_QUERY_RH_LIST.QUERY_FOR
IS
    '查询用途';
COMMENT ON COLUMN rh.RISK_MNIT_QUERY_RH_LIST.FILE_NAME
IS
    '授权书名称';
COMMENT ON COLUMN rh.RISK_MNIT_QUERY_RH_LIST.ECM_DOC_ID
IS
    '授权书ID';
COMMENT ON COLUMN rh.RISK_MNIT_QUERY_RH_LIST.QUERY_TIME
IS
    '查询时间';